### PR TITLE
update: Update financials page

### PR DESCRIPTION
**Pull request by YaosenTang**

### CODE REVIEW

**Comment by 31Hemlock** [comment]
This looks great! I only have one feedback: The text underneath "Businesses that rejected ICAF’s grant applications in 2023" is in too small of a font. The font should match the other description font on the page.

**Comment by YaosenTang** [comment]
Do you mean the line “Adobe, Comcast NBCUniversal, Libra Group, and Zoom.”?
They are actually the same font size as the description font size, just no
bold font, and it’s because Ishaq asked.

31Hemlock ***@***.***>于2024年1月31日 周三12:03写道：

**Comment by 31Hemlock** [comment]
I've emailed Dr. Ishaq to check, and he's confirmed that the font is too small. The Adobe... line just needs to be given the .section class to match the other list items.

**Comment by YaosenTang** [comment]
Actually these two lines have the same font-size. Do I need to change?


31Hemlock ***@***.***>于2024年2月2日 周五11:40写道：

**Comment by YaosenTang** [comment]
And .section class has a smaller font-size than .section-title class.

Yaosen Tang ***@***.***>于2024年2月4日 周日23:15写道：

**Pull request closed without merging**
